# Generated by Django 5.2.5 on 2025-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitorNo', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=100)),
                ('EmailAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('Phoneno', models.CharField(max_length=100)),
                ('Occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=120, null=True)),
                ('WhoToSee', models.CharField(max_length=100)),
                ('ReasonForVisit', models.TextField()),
                ('Consent', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('CheckinTime', models.TimeField()),
                ('CheckinDate', models.DateField()),
                ('CheckoutTime', models.TimeField(null=True)),
                ('VisitationDuration', models.DurationField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='Designation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
