# Generated by Django 5.2.5 on 2025-09-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitme', '0002_visitors_alter_staff_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
