# Generated by Django 5.2.5 on 2025-09-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitme', '0003_visitorphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorphoto',
            name='visitorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitme.visitors'),
        ),
    ]
