# Generated by Django 5.2.5 on 2025-09-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitme', '0004_visitorphoto_visitorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitme.visitors')),
            ],
        ),
    ]
