# Generated by Django 5.2.5 on 2025-09-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitme', '0005_visitorqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='CheckoutTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='VisitationDuration',
            field=models.CharField(null=True),
        ),
    ]
